Repository atlassian/escalator, pull requests merged in 2018-07, with the labels that each got.

#116 add extra error logging when converting memory quantities to int64
  pkg/controller/controller.go
Labels: bug

#117 Log remaining pods when pending soft delete, metrics for evicted pods
  docs/metrics.md
  pkg/controller/scale_down.go
  pkg/k8s/node_state.go
  pkg/k8s/node_state_test.go
  pkg/metrics/metrics.go
Labels: enhancement

#113 update dependencies
  Gopkg.lock
  Gopkg.toml
  README.md
  docs/best-practices-issues-gotchas.md
  pkg/controller/controller.go
  pkg/k8s/node_state.go
  pkg/k8s/node_state_test.go
Labels: task
