Repository atlassian/escalator, pull requests merged in 2019-10, with the labels that each got.

#169 #168: Untaint first when less than min nodes
  pkg/controller/controller.go
  pkg/controller/controller_scale_node_group_test.go
Labels: bug

#170 #160: Check for NodeAffinityOperator
  pkg/controller/node_group.go
  pkg/controller/node_group_test.go
  pkg/controller/scale_down_test.go
  pkg/controller/scale_up_test.go
  pkg/test/builder.go
Labels: bug

#173 regist http metrics on a new mux
  pkg/metrics/metrics.go
Labels: task

#176 Some fixes and tweaks to the Travis CI config
  .travis.yml
  Makefile
  lint.sh
Labels: task

#174 add corresponding node group name to cloud provider node group metrics
  cmd/main.go
  pkg/cloudprovider/aws/aws.go
  pkg/cloudprovider/interface.go
  pkg/controller/controller_scale_node_group_test.go
  pkg/metrics/metrics.go
  pkg/test/cloud_provider.go
Labels: enhancement
