Repository atlassian/escalator, pull requests merged in 2019-04, with the labels that each got.

#156 update slack capacity documentation
  docs/configuration/advanced-configuration.md
Labels: docs

#155 Add support to scale node group from/to 0
  docs/calculations.md
  pkg/cloudprovider/aws/aws.go
  pkg/cloudprovider/aws/aws_test.go
  pkg/cloudprovider/interface.go
  pkg/controller/controller.go
  pkg/controller/controller_scale_node_group_test.go
  pkg/controller/node_group.go
  pkg/controller/scale_down.go
  pkg/controller/scale_down_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/k8s/node_state.go
  pkg/test/cloud_provider.go
Labels: enhancement

#158 Emit 0 cpu/mem for scale up from 0
  pkg/controller/controller.go
Labels: bug
