Repository atlassian/escalator, pull requests merged in 2020-04, with the labels that each got.

#186 Housekeeping: Update dependencies
  .travis.yml
  Dockerfile
  cmd/main.go
  docs/best-practices-issues-gotchas.md
  docs/configuration/command-line.md
  docs/deployment/escalator-rbac.yaml
  go.mod
  go.sum
  pkg/controller/controller.go
  pkg/k8s/cache.go
  pkg/k8s/election.go
  pkg/k8s/node.go
  pkg/k8s/node_info.go
  pkg/k8s/node_state.go
  pkg/k8s/node_state_test.go
  pkg/k8s/taint.go
  pkg/test/node_lister.go
Labels: task

#188 Add AWS EC2 Spot functionality to Escalator
  cmd/main.go
  docs/configuration/nodegroup.md
  docs/deployment/aws/README.md
  pkg/cloudprovider/aws/aws.go
  pkg/cloudprovider/aws/aws_test.go
  pkg/cloudprovider/aws/node_group_test.go
  pkg/cloudprovider/interface.go
  pkg/controller/node_group.go
  pkg/test/aws.go
Labels: enhancement

#187 Adds Node Ignore from Deletion annotation
  docs/README.md
  docs/node-termination.md
  docs/scale-process.md
  pkg/controller/scale_down.go
  pkg/controller/scale_down_test.go
Labels: feature

#189 Add Github issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: task
